version: "3"
services:
  jenkins:
    #build: ./jenkins
    #image: chendamok/sfdc-jenkins
    image: jenkins/jenkins:lts
    # TODO: workaround, run as root use to avoid the "file permission octal value of 600" issue when running SFDX
    # Dockerfile is executed (built) before volume is mounted, you can't change permissions in mounted volume this way
    # Cannot find a way to use the defined jenkins use to run the sfdx command
    # user: root
    entrypoint: /bin/sh -c "chmod 600 /mnt/a/data01/jenkins_home/.sfdx && chmod 600 /var/jenkins_home/workspace/salesforce_demo_org/.sfdx/key.json"
    ports:
      - "8080:8080"
      - "50000:50000"
    networks:
      - netjenkinscicdsfdc
    volumes:
      # Configure bind propagation : https://docs.docker.com/storage/bind-mounts/
      - /mnt/a/data01/jenkins_home:/var/jenkins_home:rshared
      - /var/run/docker.sock:/var/run/docker.sock
  sforg:
    build: .
    image: chendamok/sforg
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    # command: "sfdx --version"
    #ports:
    #  - "3000:3000"
    networks:
        - netjenkinscicdsfdc
  postgres:
    image: postgres:9.6
    networks:
      - netjenkinscicdsfdc
    environment:
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonarpasswd
    volumes:
      # Working, no need to create the folder as it will be created automatically
      - $POSTGRES_DATA_DIR:/var/lib/postgresql/data
  sonarqube:
    image: sonarqube:lts
    ports:
      - "9000:9000"
      - "9092:9092"
    networks:
      - netjenkinscicdsfdc
    environment:
      SONARQUBE_JDBC_USERNAME: sonar
      SONARQUBE_JDBC_PASSWORD: sonarpasswd
      SONARQUBE_JDBC_URL: "jdbc:postgresql://postgres:5432/sonar"
    depends_on: 
      - postgres
networks:
  netjenkinscicdsfdc:
  