version: '3'
services:
  mydb:
    image: postgres
    volumes:
      # Working, no need to create the folder as it will be created automatically
      - $POSTGRES_DATA_DIR:/var/lib/postgresql/data
      #- /mnt/v/postgres-jenkins:/var/lib/postgresql/data
    ports:
    - 5432:5432
    environment:
      POSTGRES_PASSWORD: example