version: '2'
services:

  jenkins:
    image: jenkins/jenkins:lts
    ports:
      - "8080:8080"
      - "50000:50000"
    networks:
      - netjenkinscicdsfdc
    volumes:
      - /mnt/a/data01/jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
  
  sforg:
    build: .
    image: chendamok/sforg
    command: sfdx --version
    ports:
      - "3000:3000"
    networks:
        - netjenkinscicdsfdc

  postgres:
    image: postgres:9.6
    networks:
      - netjenkinscicdsfdc
    environment:
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonarpasswd
    #volumes:
    #  - /mnt/a/data01/postgres-data-sonar:/var/lib/postgresql/data
  
  sonarqube:
    image: sonarqube:lts
    ports:
      - "9000:9000"
      - "9092:9092"
    networks:
      - netjenkinscicdsfdc
    environment:
      SONARQUBE_JDBC_USERNAME: sonar
      SONARQUBE_JDBC_PASSWORD: sonarpasswd
      SONARQUBE_JDBC_URL: "jdbc:postgresql://postgres:5432/sonar"
    depends_on: 
      - postgres

networks:
  netjenkinscicdsfdc:
